### ISSUE TITLE
SUGGESTION !!!

### ISSUE THREAD

**Issue by Devil-panda** [swkeep/keep-crafting#1]
Script is awesome! as its a suggestion can you add support with qb-menu also it will easy for us!

**Comment by swkeep** [comment]
Hi, yea it's not an issue but converting it to qb-menu can cause some functions to not be smooth as the keep-menu version.

**Comment by on4sat** [comment]
Could you please tell me where I set the gang resistance as I should here
   gang = {
               allowed_list = {"soa"},
               allowed_grades = {"1"}
          },
put that but others gangs all  open not  resistance 1 gang

**Comment by swkeep** [comment]
you are not using it the right way. you must include gangs and their grades.
```lua
gang = {
    allowed_list = {"soa"},
    allowed_grades = { ["soa"]={ 1 } } <-- grades are numbers not strings
}
```

**Comment by on4sat** [comment]
thank you friend and it is work :)

**Comment by swkeep** [comment]
added support for qb-menu 24d159c6acc17cd5731e1959a17eb96b61d9dd84
