### ISSUE TITLE
Sry，pal，I need some help

### ISSUE THREAD

**Issue by DyroS3** [swkeep/keep-crafting#2]
before I start，I show u some info：my _qb-target_ ‘s version is 4.1.0，
so，when I use ur project，I can't interact with the table，no bug in my F8 console，or server cmd。so I need some help to use this。
HOPE U GOOD，pal，write back soon plz

**Comment by swkeep** [comment]
to be honest, your qb-target is outdated minimum version is 5.x.x. but if you have your qb-target template you can convert my script qb-target to the older version.
edit client/client_main.lua line 22.
